[package]
name = "rust-tracer"
version = "0.1.0"
authors = ["blargg <tomjankauski@gmail.com>"]
edition = "2018"

[dependencies]
cgmath = "^0.17.0"
num = "^0.2.0"

[dev-dependencies]
proptest = "0.9.2"
